/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author aryanlangeh
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class AssignAttendees extends javax.swing.JPanel {

    /**
     * Creates new form AssignAttendees
     */
    public AssignAttendees() {
        initComponents();
        combo2.removeAllItems();
        combo1.removeAllItems();
        BufferedReader br1=null;
        BufferedReader br=null;
        try {
            String attendeeid="";
            br = new BufferedReader(new FileReader("Workshop.txt"));
            br1 = new BufferedReader(new FileReader("Attendees.txt"));
            String line="";
            line=br.readLine();
            String line1="";
            String attendeename;
            line1=br1.readLine();
            String workshopid="";
            String workshopname="";
            String speakerid="";
            String place="";
            String day="";

           
            while((line1=br1.readLine())!=null)
            {
                String [] tempstringarray1 = line1.split(",");
                attendeeid=tempstringarray1[0];
                attendeename=tempstringarray1[1];
                combo1.addItem(attendeeid);//add name
            }
            while((line=br.readLine())!=null)
            {
                String [] tempstringarray = line.split(",");
                workshopid= tempstringarray[0];
                workshopname= tempstringarray[1];
                speakerid=tempstringarray[2];
                place=tempstringarray[3];
                day=tempstringarray[4];
                combo2.addItem(workshopid);
               
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(AssignAttendees.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AssignAttendees.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                br.close();
                br1.close();
            } catch (IOException ex) {
                Logger.getLogger(AssignAttendees.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        combo2 = new javax.swing.JComboBox();

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel1.setText("Attendee ID : ");

        combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Workshop ID : ");

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save)
                        .addGap(138, 138, 138)
                        .addComponent(reset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(reset))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        combo1.setSelectedIndex(0);
        combo2.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        BufferedWriter bw= null;
        try {
            bw = new BufferedWriter(new FileWriter("Assigned.txt",true));
            BufferedReader br = new BufferedReader(new FileReader("Workshop.txt"));
            BufferedReader br1 = new BufferedReader(new FileReader("Attendees.txt"));
            String line="";
            line=br.readLine();
            String line1="";
            line1=br1.readLine();
            String workshopname= (String) combo2.getSelectedItem();
            String attendeename= (String) combo1.getSelectedItem();
            String attendeeid;
            String workshopid;
            String workshopspeakerid;
            String place;
            String day;
            while((line=br.readLine())!=null)
            {
                String [] tempstringarray = line.split(",");
                if (workshopname.equals(tempstringarray[1])){
                    workshopid=tempstringarray[0];
                    workshopspeakerid=tempstringarray[2];
                    place=tempstringarray[3];
                    day=tempstringarray[4];
                    bw.write(workshopname+",");
                    bw.write(workshopid+",");
                    bw.write(workshopspeakerid+",");

                }

            }
            while((line1=br1.readLine())!=null)
            {
                String [] tempstringarray1 = line1.split(",");
                if (attendeename.equals(tempstringarray1[1])){
                    attendeeid=tempstringarray1[0];
                    bw.write(attendeename+",");
                    bw.write(attendeeid+",");
                    bw.write("\n");
                }

            }

            /*if ((workshopname.equals("Update Workshops")) || (attendeename.equals("Update Attendees"))){
                Confirmation.setText("Invalid. You left one or more fields blank.");
            }
            else
            {
                bw.write(workshopname+",");
                bw.write(attendeename+",");
                bw.write("\n");
                Confirmation.setText("Success!");
            }
            */
            bw.close();

        } catch (IOException ex) {
            Logger.getLogger(AssignAttendees.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(AssignAttendees.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo1;
    private javax.swing.JComboBox combo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
