/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static sun.lwawt.macosx.CWrapper.NSScreen.frame;

/**
 *
 * @author aryanlangeh
 */
public class Speakers extends javax.swing.JPanel {
private Component frame;
    /**
     * Creates new form Speakers
     */
    public Speakers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetS = new javax.swing.JButton();
        saveS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NameSpeaker = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Spec = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        EmailSpeaker = new javax.swing.JTextField();

        resetS.setText("Reset");
        resetS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSActionPerformed(evt);
            }
        });

        saveS.setText("Save");
        saveS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSActionPerformed(evt);
            }
        });

        jLabel4.setText("Specialization");

        jLabel1.setText("Add Speaker");

        NameSpeaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSpeakerActionPerformed(evt);
            }
        });

        jLabel3.setText("E-mail ID : ");

        Spec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Specialty", "Techincal", "Sales", "Marketing" }));
        Spec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecActionPerformed(evt);
            }
        });

        jLabel2.setText("Speaker's Name : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(saveS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetS)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EmailSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveS)
                    .addComponent(resetS))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSActionPerformed
        // TODO add your handling code here:
        NameSpeaker.setText("");
        EmailSpeaker.setText("");
        Spec.setSelectedIndex(0);
    }//GEN-LAST:event_resetSActionPerformed

    private void saveSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSActionPerformed

        try {
            int count = 1;
            BufferedReader br = new BufferedReader(new FileReader("Speakers.txt"));
            String line="";
            line=br.readLine();
            String name;
            String email;
            String specialization;
            while((line=br.readLine())!=null) /* as long as there is data in the file, it runs.
            We repeat line=br.readLine() again to ignore the header at the top of the files**/
            {
                String [] tempstringarray = line.split(",");
                count++;

            }
            specialization= (String) Spec.getSelectedItem();
            name = NameSpeaker.getText();
            email = EmailSpeaker.getText();
            BufferedWriter bw = new BufferedWriter(new FileWriter("Speakers.txt",true));
            if (NameSpeaker.getText().isEmpty() || EmailSpeaker.getText().isEmpty() || (specialization.equals("Choose Specialty"))){
                JOptionPane.showMessageDialog(frame, "Please enter data in all the fields.");
            }
            else
            {
                bw.write(count+",");
                bw.write(name+",");
                bw.write(specialization+",");
                bw.write(email+",");
                bw.write("\n");
                JOptionPane.showMessageDialog(frame, "Congrats! You are now registered with Speaker ID : " + count);

            }
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Speakers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveSActionPerformed

    private void NameSpeakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSpeakerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameSpeakerActionPerformed

    private void SpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailSpeaker;
    private javax.swing.JTextField NameSpeaker;
    private javax.swing.JComboBox Spec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton resetS;
    private javax.swing.JButton saveS;
    // End of variables declaration//GEN-END:variables
}
