/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aryanlangeh
 */
public class Workshop extends javax.swing.JPanel {

    /**
     * Creates new form Workshop
     */
    public Workshop() {
        initComponents();
        combo.removeAllItems();
        BufferedReader br1=null;
        BufferedReader br=null;
        try {
            String sID = "";
            br = new BufferedReader(new FileReader("Workshop.txt"));
            br1 = new BufferedReader(new FileReader("Speakers.txt"));
            String line= "" ;
            line=br.readLine();
            String line1= "" ;
            line1=br1.readLine();
            String sWID= "";
           
            while((line1=br1.readLine())!=null)
            {
                String [] tempstringarray1 = line1.split(",");
                sID=tempstringarray1[0];
                combo.addItem(sID);
            }
                while((line=br.readLine())!=null)
            {
                String [] tempstringarray = line.split(",");
                sWID= tempstringarray[2];
                combo.removeItem(sWID);
               
            }
           
             
           
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Workshop.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Workshop.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                br.close();
                br1.close();
            } catch (IOException ex) {
                Logger.getLogger(Workshop.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Days = new javax.swing.ButtonGroup();
        workshopName = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox();
        id = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        Thursday = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Tuesday = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Monday = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        finalMessage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        Days.add(Thursday);
        Thursday.setText("Thursday");

        jLabel1.setText("Add Workshop");

        Days.add(Tuesday);
        Tuesday.setText("Tuesday");

        jLabel4.setText("ID : (Leave Blank) ");

        Days.add(Monday);
        Monday.setText("Monday");

        jLabel6.setText("Speaker : ");

        jLabel5.setText("Name : ");

        jLabel8.setText("Day : ");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel7.setText("Place : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(save)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reset))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(145, 145, 145)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Monday)
                                        .addComponent(id)
                                        .addComponent(workshopName)
                                        .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tuesday)
                                        .addComponent(place)
                                        .addComponent(Thursday)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(finalMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(26, 26, 26)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(workshopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(Monday))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Tuesday)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Thursday)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(save)
                        .addComponent(reset))
                    .addGap(18, 18, 18)
                    .addComponent(finalMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int count=1;
        BufferedWriter bw= null;
        try {
            BufferedReader br = new BufferedReader(new FileReader("Workshop.txt"));
            String line="";
            line=br.readLine();
            String name;
            String day="";
            String location;
            String speaker;
            while((line=br.readLine())!=null) /* as long as there is data in the file, it runs.
            We repeat line=br.readLine() again to ignore the header at the top of the files**/
            {
                String [] tempstringarray = line.split(",");
                count++;
            }

            speaker= (String) combo.getSelectedItem();
            name= workshopName.getText();
            location=place.getText();
            if (Monday.isSelected()){
                day="Monday";
            }
            else if (Tuesday.isSelected()){
                day="Tuesday";
            }
            else if (Thursday.isSelected()){
                day="Thursday";
            }
            bw = new BufferedWriter(new FileWriter("Workshop.txt",true));
            if ((name.equals("")) || (speaker.equals("Update Speakers")) || (location.equals("")|| (day.equals("")))){
                finalMessage.setText("Please recheck! You left one or more fields blank.");
            }
            else
            {
                bw.write(count+",");
                bw.write(name+",");
                bw.write(speaker+",");
                bw.write(location+",");
                bw.write(day+",");
                bw.write("\n");
                finalMessage.setText("Congrats! The ID number is "+count+"");
                id.setText(""+count);
            }
            bw.close();

        } catch (IOException ex) {
            Logger.getLogger(Workshop.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Workshop.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        workshopName.setText("");
        combo.setSelectedIndex(0);
        place.setText("");
        finalMessage.setText("");
        id.setText("");
        Days.clearSelection();
    }//GEN-LAST:event_resetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Days;
    private javax.swing.JRadioButton Monday;
    private javax.swing.JRadioButton Thursday;
    private javax.swing.JRadioButton Tuesday;
    private javax.swing.JComboBox combo;
    private javax.swing.JTextField finalMessage;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField place;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField workshopName;
    // End of variables declaration//GEN-END:variables
}
